name: eamar_seller_app
# eamar_seller_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  connectivity: ^3.0.6
  dio: ^4.0.0-prev2
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  image_picker: ^0.8.0+4
  flutter_switch: ^0.3.0
  fl_chart: ^0.45.0
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_rating_bar: ^4.0.0
  flutter_typeahead: ^4.0.0
  autocomplete_textfield: ^1.7.3
  dotted_border: ^2.0.0+1
  flutter_html: ^3.0.0-alpha.2
  firebase_core: ^1.7.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.1
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.0.0
  fluttertoast: ^8.0.9
  responsive_framework: ^0.2.0
  validate_ksa_number: ^1.0.0
  file: ^6.1.4




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/cairo/Cairo-Bold.ttf
          weight: 600