name: eamar_seller_app
# eamar_seller_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  intl: any
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_switch: ^0.3.2
  fl_chart: ^0.45.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.4.1

  flutter_rating_bar: ^4.0.1
  flutter_typeahead: ^5.1.0
  autocomplete_textfield: ^2.0.1
  dotted_border: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.1.2
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.4
  responsive_framework: ^1.1.1
  validate_ksa_number: ^1.0.0
  file: ^7.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/cairo/Cairo-Bold.ttf
          weight: 600